### ISSUE TITLE
Information about propagation and consensus merging

### ISSUE THREAD

**Issue by VGrondin** [hkchengrex/Tracking-Anything-with-DEVA#1]
The paper and results are very interesting. Where in the code you perform Propagation and Consensus merging as XMem itself cannot segment new objects that appear in the scene? I've been looking in group_module.py but I'm not sure if it's where propagation and consensus is done.

**Comment by hkchengrex** [comment]
This function https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/ba826117decadece5537bf0623b6c2c11fd61760/deva/inference/inference_core.py#L139-L144

incorporates new detections.
