### ISSUE TITLE
Cannot segment and track Gundam. Any suggestion? Thanks

### ISSUE THREAD

**Issue by garrisonz** [hkchengrex/Tracking-Anything-with-DEVA#100]
Thanks for your great work!
Cannot segment and track Gundam. Any suggestion? Thanks!

input video

https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/0dc795f0-fb10-4d2c-aabe-e4ea0615f078

mask video

https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/65957dcb-0782-4eaa-863f-0be3de9bbd7d

**Comment by hkchengrex** [comment]
Unfortunately this seems to be a limitation of the image model. You can try tuning the thresholds.
