### ISSUE TITLE
How to maintain the same id when an object leaves and re-enters the field of view in a static scene? Any suggestion?

### ISSUE THREAD

**Issue by garrisonz** [hkchengrex/Tracking-Anything-with-DEVA#104]
Hi, thanks for your great work!

In the video, the tracking ID of the duck in the lower left corner changew, when it leaves and then re-enters the field of view.

How to maintain the same ID for this duck throughout the video? Any suggestion? Thanks!

The first frame in the video:
![00100](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/c30b62f5-b5b7-4f7f-a925-ec57de27effa)

The last frame in the video:
![00160](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/7e8eaff4-49a9-433b-baa0-fa02552f612d)

https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/8fb6aa8a-15be-430b-a4dc-d4a5f647594c

**Comment by hkchengrex** [comment]
Hi, by default we delete objects when they have not been detected for more than a few frames in the automatic mode. You can change this behaviour by increasing`--max_missed_detection_count``

**Comment by hkchengrex** [comment]
Please feel free to re-open if there are any updates.
