### ISSUE TITLE
Can you provide DEVA's J and F scores on the Ref-DAVIS?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#108]
Can you provide DEVA's J and F scores on the Ref-DAVIS? J&F=66.3

![Uploading image.png…]()

**Comment by hkchengrex** [comment]
Hi, you can check the pre-computed results here: https://drive.google.com/drive/u/1/folders/1BBXuNvxv5ZxGFal8ERlhfvZRkspH_MUc
