### ISSUE TITLE
ERROR: File "setup.py" not found

### ISSUE THREAD

**Issue by nasserdr** [hkchengrex/Tracking-Anything-with-DEVA#11]
I am trying to install the DEVA but getting the below error:

`pip install -e .`
==> 
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: 
~/Tracking-Anything-with-DEVA
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

```

After looking online, there are no straightforward solutions. 

Is it possible to document a more standarized installation method?

Thanks

**Comment by hkchengrex** [comment]
Upgrade your pip.
`pip install --upgrade pip`

**Comment by nasserdr** [comment]
Still getting the same error :(

**Comment by nasserdr** [comment]
Thanks 👍

**Comment by hkchengrex** [comment]
Glad it worked. I have added this in the readme.
