### ISSUE TITLE
How can I generate a gray mask?

### ISSUE THREAD

**Issue by ZhaoLongjiea** [hkchengrex/Tracking-Anything-with-DEVA#111]
When I inplement gaussian_grouping, I found DEVA is a submodule of it. And gaussian_grouping using gray mask to train. And their .sh directory is below:
python demo/demo_automatic.py \
  --chunk_size 4 \
  --img_path "$img_path" \
  --amp \
  --temporal_setting semionline \
  --size 480 \
  --output "./example/output_gaussian_dataset/${dataset_name}" \
  --use_short_id  \
  --suppress_small_objects  \
  --SAM_PRED_IOU_THRESHOLD 0.7 \

So, I would like to ask, where is the use_short_id argument used? How can I generate a gray mask with DEVA?
Thank you.

**Comment by hkchengrex** [comment]
They might have modified the code. Internally (and in some scripts) we do use a short_id parameter to separate an uint8 single-channel representation (supporting up to 255 objects) or an RGB representation that supports much more. By default, we use the RGB one for the demo. If you wish, you can convert the output to "short id" fairly easily by reading all the masks, finding the unique RGB values, and remapping them to 0~255.
