### ISSUE TITLE
hello,I would like to know how to submit the result about refer youtube

### ISSUE THREAD

**Issue by wqqqqq0720** [hkchengrex/Tracking-Anything-with-DEVA#112]
Can you tell me how to submit the result, I have not responded after clicking submit
<img width="1004" alt="截屏2024-09-05 上午11 13 35" src="https://github.com/user-attachments/assets/eec6caff-0407-4823-bece-054f01839071">

**Comment by hkchengrex** [comment]
I do not host this evaluation server, so you should ask the Ref-YouTubeVOS organizers.
That being said, from https://github.com/codalab/codalab-competitions/issues/3503, using Firefox might solve the problem.
