### ISSUE TITLE
Can you provide detailed testing code and instructions for YouTubeVIS

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#113]
Can you provide detailed testing code and instructions for YouTubeVIS

**Comment by hkchengrex** [comment]
As it is not part of our main results we did not emphasize it in this repo. The evaluation process follows this section: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/EVALUATION.md#open-worldlarge-vocabularyunsupervised-video-object-segmentation -- the exact same code was used. Similarly, the detections are computed per frame, and then propagated with `eval_with_detections.py`.
