### ISSUE TITLE
semantic labeling for automated segmentation

### ISSUE THREAD

**Issue by tzayuan** [hkchengrex/Tracking-Anything-with-DEVA#114]
Hi @hkchengrex ,

I run
```
python demo/demo_automatic.py --chunk_size 4 \
--img_path ./example/vipseg/images/12_1mWNahzcsAc \
--amp --temporal_setting semionline \
--size 480 \
--output ./example/output
```

and I got below results:
![image](https://github.com/user-attachments/assets/ae9e3bc3-6c89-4aab-bf75-94f5e7462292)

Is this segmentation graph semantically labeled? If not, are there any suggestions for assigning a label to each instance of the segmentation graph?

**Comment by hkchengrex** [comment]
Hi, 

The automatic demo uses SAM, which does not provide semantic categories.
