### ISSUE TITLE
Issue with Running Deva Code for Rain Video Segmentation

### ISSUE THREAD

**Issue by parisanaqdi** [hkchengrex/Tracking-Anything-with-DEVA#116]
Hello REX,
Thank you for sharing Deva; I appreciate your work on this video segmentation code.
I recently ran Deva on Google Colab and tested it with a video containing rain droplets.However,it didn't seem to work as expected for this scenario.Could you please let me know if  you've tested Deva with videos containing rain?Does the current model handle rain droplet segmentation effectively,or would you recommend additional steps?

Additionally,is it possible to fine_tune Deva to segment specific motion objects in a video,like rainfalls?
Also,if you are aware  of any libraries or techniques specifically for segmentation rain droplets,I'd greatly appreciate your guidance.

Thank you very much for your help.

**Comment by hkchengrex** [comment]
Hi, thanks for your interest!
The performance would be highly dependent on the image-level detector and the tracker -- rainfalls seem to be something that is very hard for those models. You would probably need a good "rainfall" detector first. Unfortunately, I am not aware of any.
