### ISSUE TITLE
CUDA_HOME

### ISSUE THREAD

**Issue by 21pl** [hkchengrex/Tracking-Anything-with-DEVA#15]
I must be doing something very stupid but what do I set CUDA_HOME to if I am installing pytorch and cuda via a conda environment as everything I've tried doesn't seem to get the Grounding Dino to install correctly.

**Comment by hkchengrex** [comment]
We did not change anything related to installation for Grounding DINO. Since there are many users there, you might find better help at https://github.com/IDEA-Research/Grounded-Segment-Anything regarding installation issues.

**Comment by Prasantkumar987** [comment]
Added it in #18, this will help you set CUDA_HOME as a env variable
