### ISSUE TITLE
how can I enable cpu to run the demo_gradio.py

### ISSUE THREAD

**Issue by huyuaaaray** [hkchengrex/Tracking-Anything-with-DEVA#17]
Hi, I don't have any cuda gpu, but i still want to run this project on my computer. What should i edit about  this file to reproduce?

**Comment by hkchengrex** [comment]
You can globally search "cuda" and replace each occurrence. There shouldn't be many.

**Comment by huyuaaaray** [comment]
just in the demo_gradio file? I either delete 'cuda' or replace to 'cpu', still didn't work.

**Comment by hkchengrex** [comment]
In that file and (recursively) the functions that it calls.

**Comment by huyuaaaray** [comment]
Ok, just delete all the cuda?
________________________________
发件人: Rex Cheng ***@***.***>
发送时间: Monday, September 18, 2023 10:51:28 PM
收件人: hkchengrex/Tracking-Anything-with-DEVA ***@***.***>
抄送: Hu, Yu ***@***.***>; Author ***@***.***>
主题: Re: [hkchengrex/Tracking-Anything-with-DEVA] how can I enable cpu to run the demo_gradio.py (Issue #17)

[External Email]

In that file and (recursively) the functions that it calls.

―

**Comment by hkchengrex** [comment]
Exercise judgment but that's the idea.
