### ISSUE TITLE
Insufficient GPU memory

### ISSUE THREAD

**Issue by configA** [hkchengrex/Tracking-Anything-with-DEVA#19]
When running the example routine with the following command:

python demo/demo_with_text.py --chunk_size 1
--img_path ./example/vipseg/images/12_1mWNahzcsAc
--amp --temporal_setting semionline
--size 480
--output ./example/output --prompt person.hat.horse

I encountered the following error:
"RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 5.93 GiB total capacity; 4.73 GiB already allocated; 337.75 MiB free; 4.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF."

My GPU is GTX 1060 6GB. What could be the possible reasons for this issue? How can I resolve it?

**Comment by hkchengrex** [comment]
At which step does this happen?

**Comment by hkchengrex** [comment]
Closed as stale.
