### ISSUE TITLE
video tracking initialization 

### ISSUE THREAD

**Issue by liruiw** [hkchengrex/Tracking-Anything-with-DEVA#2]
Thanks for releasing this great repo. May i ask how to initialize the video segmentation with point prompt on SAM. I only found an [auto-segment  ](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/ext/automatic_sam.py#L47) function for SAM in the codebase. I am also curious about the behavior of consensus under the online setting where images come in a stream.

**Comment by hkchengrex** [comment]
We currently only use SAM in two ways: 1) segment using bounding boxes obtained from GroundingDINO (i.e., text-prompt), and 2) segment using grid-like point prompts (i.e., automatic).

I assume by point prompt you meant non-grid-like ones. Then I think our current grid-like demo would be a good place to start: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/demo/demo_automatic.py and https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/ext/automatic_sam.py.

In-clip consensus is not considered in the online setting. Semi-online introduces a bounded frame delay from the input stream to the output.
