### ISSUE TITLE
Some confusion about Table S1

### ISSUE THREAD

**Issue by csustYyh** [hkchengrex/Tracking-Anything-with-DEVA#22]
Congratulations and respect for your excellent work!
About Table S1, I wonder whether the ‘w/ OVIS’ means train DEVA with OVIS, and 'DEVA' denotes XMem + SAM(bi-directional propagation) or XMem + modifications in Appendix Section A.
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/118873316/d5be6b2e-f41f-42b0-b737-4720a3ae7d28)

**Comment by hkchengrex** [comment]
Detection models are not used for video object segmentation evaluation. We do call modified XMem "DEVA" as well.

**Comment by csustYyh** [comment]
Thanks for your guidance.
