### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by AK51** [hkchengrex/Tracking-Anything-with-DEVA#26]
Hi,

For my dataset, I have about 100 from Labelme segmentation.
After that, what is the proper way to train the model?
Shall I follow this? Is it for training? Thx
https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/EVALUATION.md
Then python evaluation/eval_vos.py --dataset [dataset] --output [output directory]

**Comment by hkchengrex** [comment]
As the title suggests, it is for evaluation.

You would need to format your data like one of ours and modify all relevant code to load your data.
In general, we cannot give step-by-step guidance as the process depends on your data/desired augmentation, etc. 
It should be fairly straightforward if it is sufficiently similar to existing datasets.
