### ISSUE TITLE
Using Postive and negative points for each object as prompts

### ISSUE THREAD

**Issue by MahdiKoochali** [hkchengrex/Tracking-Anything-with-DEVA#27]
Hi,

I was trying to pass positive and negative points as prompts to the model [Positive points: inside object, Negative: outside object]

Can you give me some help to do this?

Thanks

**Comment by hkchengrex** [comment]
This seems to be an application for extending SAM or interactive image segmentation like [f-BRS](https://github.com/SamsungLabs/fbrs_interactive_segmentation). Please refer to our current two demos to extend new image models with DEVA.
