### ISSUE TITLE
VRAM needed

### ISSUE THREAD

**Issue by sebastianelsner** [hkchengrex/Tracking-Anything-with-DEVA#30]
Hi!

I am getting good results with this project! Thank you!

currently I am running on a RTX 3090 with a 24GB of VRAM. I am running the automatic mode demo script on two different image sequences with both 2048x1080 resolution, both png, both RGB, both 101 frames long. The weird thing is: One image sequence is completing the script, the other one is giving a `CUDA out of memory` exception. I have tried systematically changing the chunk_size, size and many other parameters, but there seems to be no impact at all.

Maybe someone would be so kind to point me in the right direction: 
* what  tools to use to debug this
* maybe shed some light what internals could cause this behaviour
* what are the VRAM requirements?
* 
Thank you!

**Comment by hkchengrex** [comment]
Memory consumption comes from two parts: 1) a constant cost used by the image model and the propagation model (scale with chunk size and resolution), and 2) a linear cost w.r.t. to the number of objects (and resolution) in memory.

It seems like that (2) is giving you problems. Can you try reducing `max_num_objects`?
Not sure if you have already, but specifying `--amp` also helps a lot.

**Comment by hkchengrex** [comment]
This looks weird. Can you provide more info? Like when does it become blank? Can you post the output video?
