### ISSUE TITLE
NameError: name '_C' is not defined

### ISSUE THREAD

**Issue by biechifanle** [hkchengrex/Tracking-Anything-with-DEVA#32]
A lot of problems with the code on colab have been corrected. The remaining compilation problem remains, and I don’t know how to deal with it.
![微信图片_20231009105201](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40875540/b32c6fef-ce28-4d76-bd9b-f172daba8442)

**Comment by hkchengrex** [comment]
Most likely you did not install grounded-sam properly. See also https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15
