### ISSUE TITLE
How to reproduce VIP-Seg results

### ISSUE THREAD

**Issue by lxtGH** [hkchengrex/Tracking-Anything-with-DEVA#33]
Hi! Thanks open source the code and along with the great demo.

I just wonder how to reproduce your Video K-Net results with the DEVA on VIP-Seg.

Best Regards!
Xiangtai

**Comment by hkchengrex** [comment]
Hi, thanks for your code too :)

See here: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/EVALUATION.md#open-worldlarge-vocabularyunsupervised-video-object-segmentation

The detections from Video-K-Net can be found here: https://drive.google.com/drive/folders/1iBJBoKZAFaNYM_6uwBR0Vvc6q0nHXbFR?usp=sharing
