### ISSUE TITLE
fine-tune static image for medical domain

### ISSUE THREAD

**Issue by yarinbar** [hkchengrex/Tracking-Anything-with-DEVA#34]
Hi,
Thanks to your recommendation i am looking at this repository as a backbone to my work.
We are trying to see if domain specific adaptations can be made to enhance the model's performance (specifically, medical image segmentation).

There is little written in both XMem and DEVA about how the pretraining process.

We have a labeled dataset of non-consecutive frames taken from a clip and want to somehow improve DEVA's capability on the in-between frames.

I think the best course of action would be using the static-image-pretraining to do that but i am not clear on how I should go about it.

Any help or a nudge in the right direction would be appreciated!

**Comment by hkchengrex** [comment]
The pre-training step is proposed in STM so we did not go into details in our papers.
You can start by looking at [the dataset implementation](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/dataset/static_dataset.py) and try to finetune the final model with stage 0 (static image pre-training). 
That is, after adding your own data, run
```
python -m torch.distributed.run --master_port 25763 --nproc_per_node=8 deva/train.py --exp_id deva_finetune --stage 0 --load_network [path to the pretrained network]
```

**Comment by yarinbar** [comment]
Thanks! 
I see the data is cropped and resized to 338 pixels, my data is 512 natively and has very delicate objects (some a few pixels wide) - so resizing would definitely hurt the annotations. Is the size crucial for the model and fps? Or could i change the input size to fit my data image size?

Our data is annotated frames from a video 15 frames apart. Do you reckon we could use that for full training? I saw the increments start from 1 frame and go up progressively but we can only start from 15. 

Thanks so much for your help!

**Comment by hkchengrex** [comment]
You can change the input size during training -- it does not affect the size during inference.
15 frames apart should still be useable for main training.
