### ISSUE TITLE
uvos

### ISSUE THREAD

**Issue by starandharry** [hkchengrex/Tracking-Anything-with-DEVA#36]
Hello, this is a wonderful work. I read your paper and found that it was mentioned that your model can be used to do many tasks. For example, unsupervised video object segmentation. Can this be implemented in the code? If so, what is the command or code?And how can I train it？
thankyou very much！

**Comment by hkchengrex** [comment]
See https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/EVALUATION.md#open-worldlarge-vocabularyunsupervised-video-object-segmentation
