### ISSUE TITLE
Advice on optimizing use?

### ISSUE THREAD

**Issue by manolilab** [hkchengrex/Tracking-Anything-with-DEVA#37]
Hi DEVA team! Thank you for this fantastic resource and repo. It is clear that DEVA already works really well by default. However, I noticed a few fault modes that arose in my specific use case, which involves detecting and tracking two similar-looking animals of the same species in a closed chamber. Animals cannot leave or enter the chamber.

1) Is it possible to feed in manually curated segmentation for the first frame (or for arbitrary frames) in a video clip? I've noticed that errors in segmentation of the initial frame get propagated over time, so being able to supply manually curated segmentation for known challenging frames (especially at the start of video clips) may dramatically improve overall results.

2) If I segment 1000 consecutive frames forwards and backwards (by reversing the numbering of the frames in a folder), I may get different segmentation results. The direction in which the first frame is easily segmentable yields the better video segmentation overall result. Is this surprising? Or perhaps is this not surprising despite bidirectional propagation because the extended 1000-frame length exceeds the time horizon of bidirectional propagation?

3) Since the number of objects I wish to detect (e.g., two) is constant over the entire video, is there a set of parameters that is functionally equivalent to setting the hypothetical variable min_num_objects to two? (I already set max_num_objects to two, and I recognize that min_num_objects does not exist as a variable in the repository.)

4) Is there a way to set a maximum mask size or area, since I've noticed that DEVA occasionally lumps together one animal's tail with another animal's body as a single segment, even if the two animals are not in direct physical contact.

Many, many thanks!
Shuyu

**Comment by hkchengrex** [comment]
Hello, thank you for your interest.
For your use case, it seems like you are tracking two objects, that are constantly visible, and manually supplying at least one frame is not a problem. I think this is better suited to a video object segmentation pipeline. We do have a recent project [Cutie](https://github.com/hkchengrex/Cutie) that works well for this task. There is a GUI that you can quickly try on your data. DEVA is designed to be flexible and might not be the best in these curated settings.

To answer your specific questions, 
1. Yes. Some code editing is probably needed.
2. This is not surprising. The initial conditions matter a lot.
3/4: No. Not sure how they can be potentially implemented.
