### ISSUE TITLE
Question regarding inference

### ISSUE THREAD

**Issue by JawadTawhidi** [hkchengrex/Tracking-Anything-with-DEVA#41]
Hi, I have my own model for unsupervised video object segmentation, but the main problem with my model is that it is just considering short term temporal information, so that I want to use DEVA's temporal propagation model to propagate the temporal information. 

Now, how can I use DEVA's temporal propagation model for this purpose? If I generate the segmentation masks using my own model and then run the DEVA's temporal propagation model separately on the generated segmentation masks, is this method true?

**Comment by hkchengrex** [comment]
Yes, you can use it that way.

**Comment by JawadTawhidi** [comment]
Thanks, but I am a bit confused even after checking the commands. For example my model is generating masks which are saved in one folder, under that folder I have many subfolders which contain the masks, now how to run DEVA's temporal propagation on these segmentation masks. I saw a sample in example/vipseg which has a format of one folder is the original images and another is the segmentation masks. But mine has different structure.

**Comment by hkchengrex** [comment]
You don't need the JSON files if you don't expect those meta information to be propagated to the output. You can delete the JSON files in the example and it should still work (I just pushed a fix on a minor visualization bug for this). For the directory structure, I don't see a problem with yours.

**Comment by JawadTawhidi** [comment]
Ok, Thank you so much. 

As I checked my directory structure it is similar to DAVIS-2016. My model is also for unsupervised video object segmentation. So what if I just put my data instead of DAVIS-2016 for temporal propagation? I mean the method you specified for unsupervised video object segmentation on DAVIS-2016, can I just put my data set and the segmentation masks instead of DAVIS-2016 and follow the commands?

**Comment by hkchengrex** [comment]
DAVIS-16 is much more like a "salient video object segmentation" with only one object. If that suits your needs.

**Comment by JawadTawhidi** [comment]
My data set has single object in some videos, but in some videos it has more than one objects. 

But the model which I have used to segment the videos is actually proposed for Davis-16, youtube objects and FBMS.

**Comment by hkchengrex** [comment]
You can certainly try. I personally would not expect single-object saliency to extend to multi-object but you are probably much more informed on the type of data and model that you are working with.
