### ISSUE TITLE
Error while calculating J&F value

### ISSUE THREAD

**Issue by JawadTawhidi** [hkchengrex/Tracking-Anything-with-DEVA#42]
Hi, I downloaded your Pre-computed detections from image models(I downloaded the Unsup-DAVIS16-DEVA-DIS). I just want to give these results to DAVIS16 official code to regenerate the J and F values, I am using this official comman:

python tools/eval.py -i path-to-my-technique -o results.yaml --year 2016 --single-object --phase val

 but this error comes:

[WARNING][24-11-2023 14:26:00] Temporal stability not available
[INFO][24-11-2023 14:26:00] Loading DAVIS year: 2016 phase: phase.VAL
[INFO][24-11-2023 14:26:00] Loading video segmentations from: Deva
Traceback (most recent call last):
  File "python/tools/eval.py", line 80, in <module>
    osp.join(args.input,s),args.single_object) for s in db.iternames()]
  File "/home/users/JawadT/davis-2017/python/lib/davis/dataset/base.py", line 127, in __init__
    self.n_objects = _get_num_objects(self[0])
  File "/home/ubuntu/anaconda3/envs/Second/lib/python2.7/site-packages/skimage/io/collection.py", line 264, in __getitem__
    self.data[idx] = self.load_func(fname, **kwargs)
  File "/home/users/JawadT/davis-2017/python/lib/davis/dataset/base.py", line 27, in _load_annotation
    annotation,_ = imread_indexed(filename)
  File "/home/users/JawadT/davis-2017/python/lib/davis/misc/io.py", line 13, in imread_indexed
    return annotation,np.array(im.getpalette()).reshape((-1,3))
ValueError: cannot reshape array of size 1 into shape (3)

**Comment by JawadTawhidi** [comment]
While it is working for results which are generated by other models.

**Comment by hkchengrex** [comment]
There are many ways to format the same output. The code that you are using is not maintained anymore iirc and expects a palette which we do not generate. You can use the eval code that we recommended in the documentation or implement it yourself w/ reference: https://github.com/davisvideochallenge/davis2017-evaluation/issues/4
