### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JawadTawhidi** [hkchengrex/Tracking-Anything-with-DEVA#43]
Hi, sorry for asking so much questions. I want to implement the DEVA’s temporal propagation model for 2 tasks:

1.I have downloaded your pre computed detections from image models(For DAVIS16), now I want to implement DEVA’s temporal propagation model and then regenerate the J and F values.
2.I have generated some detections by my own model, I just want to use DAVIS16 approach to propagate the temporal information. 

What I did is:

1-I installed python 3.8 
2-I installed the latest version of Pytorch and corresponding torchvision
3-I cloned your repo
I did run pip install -e . command
4-Then downloaded pretrained models
5-Then I did run this command:

python evaluation/eval_saliency.py --mask_path UnsupDAVIS16/Unsup-DAVIS16-DIS-detections --img_path DAVIS/JPEGImages --output 24output --imset_path DAVIS/ImageSets/2016/val.txt

But I am getting this error:

Traceback (most recent call last): File "/home/users/JawadT/Tracking-Anything-with-DEVA/evaluation/eval_saliency.py", line 13, in <module> from deva.inference.data.saliency_test_datasets import DAVISSaliencyTestDataset ModuleNotFoundError: No module named 'deva' 

What should I do solve it? Do I need to install more packages? Even for DAVIS2016 I have to install fork of Grounded-Segment-Anything?

**Comment by hkchengrex** [comment]
That error appears if you have not installed deva. Can you check if you can `import deva`?

**Comment by JawadTawhidi** [comment]
Hi, I did the following thigs: 

1-I installed python 3.8
2-I installed the latest version of Pytorch and corresponding torchvision
3-I cloned your repo

but when I run pip install -e . command, this error is coming:

Obtaining file:///home/users/JawadT/Tracking-Anything-with-DEVA
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting thinplate@ git+https://github.com/cheind/py-thin-plate-spline (from deva==1.0.0)
  Cloning https://github.com/cheind/py-thin-plate-spline to /tmp/pip-install-bru6by98/thinplate_7a522d82876d4738acc5c71297cc691a
  Running command git clone --filter=blob:none --quiet https://github.com/cheind/py-thin-plate-spline /tmp/pip-install-bru6by98/thinplate_7a522d82876d4738acc5c71297cc691a
  Resolved https://github.com/cheind/py-thin-plate-spline to commit f6995795397118b7d0ac01aecd3f39ffbfad9dee
  Preparing metadata (setup.py) ... done
Collecting gdown>=4.7.1 (from deva==1.0.0)
  Using cached gdown-4.7.1-py3-none-any.whl (15 kB)
Collecting gitpython>=3.1 (from deva==1.0.0)
  Using cached GitPython-3.1.40-py3-none-any.whl.metadata (12 kB)
Collecting gradio>=3.44 (from deva==1.0.0)
  Using cached gradio-4.7.1-py3-none-any.whl.metadata (17 kB)
Collecting gurobipy>=10.0.3 (from deva==1.0.0)
  Using cached gurobipy-10.0.3-cp38-cp38-manylinux2014_x86_64.whl.metadata (15 kB)
Collecting hickle>=5.0 (from deva==1.0.0)
  Using cached hickle-5.0.2-py3-none-any.whl (107 kB)
Requirement already satisfied: numpy>=1.22 in /home/ubuntu/anaconda3/envs/jawad/lib/python3.8/site-packages (from deva==1.0.0) (1.24.3)
Collecting opencv-python>=4.8 (from deva==1.0.0)
  Using cached opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: pillow>=9.5 in /home/ubuntu/anaconda3/envs/jawad/lib/python3.8/site-packages (from deva==1.0.0) (10.0.1)
Collecting pulp>=2.7 (from deva==1.0.0)
  Using cached PuLP-2.7.0-py3-none-any.whl (14.3 MB)
Collecting pycocotools>=2.0.7 (from deva==1.0.0)
  Using cached pycocotools-2.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.1 kB)
INFO: pip is looking at multiple versions of deva to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.11.4 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement scipy>=1.11.2 (from deva) (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1)
ERROR: No matching distribution found for scipy>=1.11.2

**Comment by hkchengrex** [comment]
Ah, it seems like Python 3.8 is not enough for that version of scipy. Can you try with Python 3.9 instead? Sorry about this. I have updated the readme to reflect this requirement. Alternatively, you can use an older scipy -- mostly it would still work,

**Comment by JawadTawhidi** [comment]
Thank you, it worked. But now when I want to run this command python evaluation/eval_saliency.py --mask_path Unsup-DAVIS16/Unsup-DAVIS16-DIS-detections --img_path DAVIS/JPEGImages --output 28output --imset_path DAVIS/ImageSets/2016/val.txt


This is error is coming:



Traceback (most recent call last):
  File "/home/users/JawadT/Tracking-Anything-with-DEVA/evaluation/eval_saliency.py", line 31, in <module>
    network, config, args = get_model_and_config(parser)
  File "/home/users/JawadT/Tracking-Anything-with-DEVA/deva/inference/eval_args.py", line 65, in get_model_and_config
    network = DEVA(config).cuda().eval()
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 918, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/nn/modules/module.py", line 918, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/ubuntu/anaconda3/envs/jawad/lib/python3.9/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by hkchengrex** [comment]
Your installed pytorch is not CUDA-enabled. See https://pytorch.org/

**Comment by JawadTawhidi** [comment]
Thank you, solved.
