### ISSUE TITLE
Unexpected segmentation output

### ISSUE THREAD

**Issue by JawadTawhidi** [hkchengrex/Tracking-Anything-with-DEVA#46]
Hi, I generated some detections using my own model, then I wanted to Use DEVA's temporal propagation approach to propagate temporal information, but after running the DEVA's temporal propagation model, the output becomes totally different and the mean of J and F is 8. I am confused if DEVA is accepting any kind of detection.
This is the segmentation before applying DEVA:
![BeforeDeva](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/1353c0f8-02f1-4fd6-a7c5-cb8c97dfd355)

And this is the segmentation mask after applying DEVA:

![afterdeva](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/e30398f7-3d0e-40af-badc-d9c879db1165)

**Comment by hkchengrex** [comment]
There is not enough information for me to figure out what is going on here. Can you start from the provided examples and see if they work? If they do, what are the differences between your output with the examples? Figuring out and correcting those differences will likely solve your problem.

**Comment by hkchengrex** [comment]
Can you start from the provided examples and see if they work? If they do, what are the differences between your output with the examples? Figuring out and correcting those differences will likely solve your problem.

**Comment by JawadTawhidi** [comment]
Right now the difference which I see is that my detections are colored and yours are not.

**Comment by hkchengrex** [comment]
The coloring only partially reflects the underlying data structure and representation. You can inspect what the dataloader sees by opening the image with PIL.

**Comment by hkchengrex** [comment]
Closed due to inactivity.
