### ISSUE TITLE
Is ovis used for training networks? Do you have a download link？

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#47]
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/65eda3ec-b0ac-462f-8797-02ab18fa078e)

**Comment by hkchengrex** [comment]
I have just updated the docs. Can you check again: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/TRAINING.md?

**Comment by hkchengrex** [comment]
As mentioned in the paper, we only train the temporal model. Please find the differences with XMem in the appendix.
I do not understand your last question.

**Comment by longmalongma** [comment]
> As mentioned in the paper, we only train the temporal model. Please find the differences with XMem in the appendix. I do not understand your last question.

When were these big models like sam used? Only for testing? We need to save sam's reasoning mask first, right?

**Comment by hkchengrex** [comment]
Only for testing. Yes.
