### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by KnSun99** [hkchengrex/Tracking-Anything-with-DEVA#48]
Hi,
I try to train the model.

Run:  deva/train.py
data:  download_datasets.py

Sets: 
import os
os.environ["MASTER_ADDR"] = 'localhost'
os.environ["MASTER_PORT"] = "12355"
os.environ['CUDA_LAUNCH_BLOCKING'] = "1" 

The following errors were reported during training:

class ###############################################################################
<class 'torch.Tensor'> <class 'torch.Tensor'> <class 'torch.Tensor'> <class 'torch.Tensor'> <class 'dict'>

len ###############################################################################
16 16 16 16 2
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [680,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):

  File ~/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/train.py:270
    model.do_pass(data, total_iter)

  File ~/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/model/trainer.py:155 in do_pass
    losses = self.loss_computer.compute({**data, **out}, num_filled_objects, it)

  File ~/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/model/losses.py:62 in compute
    loss, p = self.bce(data[f'logits_{ti}'][bi:bi + 1, :num_objects[bi] + 1],

  File ~/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/nn/modules/module.py:1518 in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)

  File ~/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/nn/modules/module.py:1527 in _call_impl
    return forward_call(*args, **kwargs)

  File ~/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/model/losses.py:34 in forward
    return F.cross_entropy(input, target), 1.0

  File ~/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/nn/functional.py:3053 in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)

RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Is this a question of the number of categories, or something else?
How to fix it?

Thanks

**Comment by hkchengrex** [comment]
Are you hardcoding the configuration? Does the original (unmodified) script work?

**Comment by KnSun99** [comment]
I modified the data root directory.
And modified torch.distributed because there is only one GPU.

**Comment by hkchengrex** [comment]
Does the original (unmodified) script work?

**Comment by KnSun99** [comment]
Also report an error.

python -m torch.distributed.run --master_port 25763 --nproc_per_node=1 deva/train.py --exp_id deva_retrain --stage 03

An error was reported during an iteration.
Error message:

../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [598,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [599,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [600,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [601,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [602,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [603,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [604,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/NLLLoss2d.cu:103: nll_loss2d_forward_kernel: block: [0,0,0], thread: [605,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/train_sh.py", line 251, in <module>
    model.do_pass(data, total_iter)
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/model/trainer.py", line 159, in do_pass
    self.integrator.add_dict(losses)
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/utils/log_integrator.py", line 39, in add_dict
    self.add_tensor(k, v)
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/utils/log_integrator.py", line 35, in add_tensor
    self.values[key] += tensor.mean().item()
                        ^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[W CUDAGuardImpl.h:115] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
[2023-12-06 14:25:32,820] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 0 (pid: 350757) of binary: /home/lh/Software/Anaconda3/envs/DEVA/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
deva/train_sh.py FAILED
-------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-12-06_14:25:32
  host      : lh49
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 350757)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 350757
=======================================================

**Comment by hkchengrex** [comment]
There is still a `train_sh.py` that I don't recognize so this is not the unmodified code.

Anyway, the first error indicates that the number of classes in the ground truth does not match that of the prediction. You can start by inspecting them. I hope it is understandable that I cannot debug code written/modified by you.

**Comment by KnSun99** [comment]
I debugged it again and there was another error. It came up during training.
Seems to be a data reading problem.

Error：

Network saved to /home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/scripts/saves/Dec07-17.27.13-deva_retrain-s0/deva_retrain-s0_5K.pth.
Checkpoint saved to /home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/scripts/saves/Dec07-17.27.13-deva_retrain-s0/deva_retrain-s0_checkpoint_5K.pth.
Traceback (most recent call last):
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/train.py", line 240, in <module>
    for data in train_loader:
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 13.
Original Traceback (most recent call last):
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lh/Software/Anaconda3/envs/DEVA/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/lh/NAS/home/code/SAM/Tracking-Anything-with-DEVA-main/deva/dataset/static_dataset.py", line 169, in __getitem__
    first_frame_gt[0, i] = (this_mask[0])
    ~~~~~~~~~~~~~~^^^^^^
IndexError: index 1 is out of bounds for axis 1 with size 1


How do I solve this? Thank you.

**Comment by hkchengrex** [comment]
I am pretty sure that this is still a modified code (the line number does not match). I did a fresh clone and training still works out of the box. Can you please try to do a fresh clone and see if it works? I think debugging would be much easier for you if we know what works and what doesn't.

As mentioned, the error indicates that the number of classes in the ground truth does not match that of the prediction. You can start by inspecting them. I hope it is understandable that I cannot debug code written/modified by you.

**Comment by hkchengrex** [comment]
I cannot reproduce this. Can you inspect the number of classes in the ground truth and that of the prediction?

**Comment by KnSun99** [comment]
I'll try downloading the training set again.
And then train and test it.

**Comment by KnSun99** [comment]
The previous mistake did not appear again for the time being.
Now complete the training of stage=0；Start training stage=3, CUDA out of memory occurs
As follows:
    torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 23.64 GiB of which 22.94 MiB is free. Process 2298 has 390.70 MiB memory in use. Including non-PyTorch memory, this process has 22.96 GiB memory in use. Of the allocated memory 22.01 GiB is allocated by PyTorch, and 321.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

YouTube dataset size: 3464
DAVIS dataset size: 60
OVIS dataset size: 507
Concat dataset size: 5285
Renewed with max_skip=5
We approximately use 455 epochs.
The skip value will change approximately at the following iterations: [15000, 45000, 120000]


What parameters can be adjusted?
I tried to adjust some parameters, but it still doesn't work.

NVIDIA GeForce RTX 4090 (one card)

**Comment by hkchengrex** [comment]
You can reduce the batch size (which affects performance to an unknown degree), use more GPUs, or implement gradient accumulation (not implemented here).
