### ISSUE TITLE
About training details

### ISSUE THREAD

**Issue by csustYyh** [hkchengrex/Tracking-Anything-with-DEVA#50]
When training w/o OVIS, 
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/118873316/963353ad-de82-43ef-84ad-09aea3310c7f)
whether the DEVA's training settings are the same as described in this paper,
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/118873316/1bcd2c46-9979-4732-accb-4fe90e7436ce)
or in XMem?
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/118873316/60da50e3-ccb6-4b2e-925c-c90e527f1b3d)

**Comment by hkchengrex** [comment]
As in the paper. The number of iterations is reduced accordingly such that the number of epochs is roughly the same.
