### ISSUE TITLE
Is it normal for DEVA's training speed to be much slower than XMem? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#52]
Is it normal for DEVA's training speed to be much slower than XMem? I am training DEVA on the same machine and in the same environment, but the speed is very slow. I don't know why.

**Comment by longmalongma** [comment]
Does anyone else have this problem?

**Comment by hkchengrex** [comment]
The training parameters are different so I would expect there to be some differences.

**Comment by longmalongma** [comment]
> The training parameters are different so I would expect there to be some differences.

But now my training speed for DEVA is more than 10 times slower than training for XMem, is this normal? Is there any solution? I cannot reproduce DEVA at this speed.

**Comment by hkchengrex** [comment]
The training speed depends on various factors. I think the general rule is that if your GPU has high utilization (and high power consumption), it is doing fine.

**Comment by longmalongma** [comment]
> The training speed depends on various factors. I think the general rule is that if your GPU has high utilization (and high power consumption), it is doing fine.

My gpu usage is almost zero now, mainly because I am stuck in reading data for a long time,
