### ISSUE TITLE
Not working if there is large variation between consecutive frames??

### ISSUE THREAD

**Issue by JawadTawhidi** [hkchengrex/Tracking-Anything-with-DEVA#53]
Hi, I tried DEVA on some ultrasound data sets, it is not working well as there is large variation between consecutive frames. It seems if there is much differences between the object shape and size in consecutive frames, it is not possible for deva to reach in-clip consensus. 

My model's result is 66.7, but when I use DEVA's temporal propagation model to propagate temporal information, the result decrease to 39.

My data set has single object for most of the videos, but for some videos it has multiple objects, I used your approach for both davis 2016 and also davis 2017. When I used davis 2017 approach, I used https://github.com/davisvideochallenge/davis2017-evaluation for calculating J and F values, and when I used davis 2016 approach I used https://github.com/hkchengrex/vos-benchmark for calculating J and F values.

Do you think I am making any mistake here? or I am right when the differences between consecutive frames are so much, it will be very difficult even it will be impossible for deva to reach in-cli Consensus?

**Comment by JawadTawhidi** [comment]
![00000](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/22714db3-b027-4a66-a620-f8509238cd49)
![00001](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/393af9f8-1640-43e3-bd68-3a32d873924e)
![00002](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/be5472d7-d41a-4748-a6df-e5c338374878)
![00003](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/2e35b531-bdb5-46bd-899f-ee921e1bbe0a)
![00004](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/b13ac660-e6e5-4b30-b0f1-e8f6b0afd299)
![00005](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/c7ab4aef-7f4a-4481-ba2e-96b011681cb1)
![00006](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/2b181525-c182-49a3-b7f8-5cacd7c5ce86)
![00007](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/b7479660-2d85-4baf-bf91-cd271ef9e460)
![00008](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/27ee9e4d-1559-48e6-9cac-5ed52f7e4971)
![00009](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/02f1d2c7-8833-4c3f-bd03-93699640f9f0)

**Comment by JawadTawhidi** [comment]
As an example here I have uploaded 10 first frames from a video of my data set, I think the reason which DEVA is not performing good on my data set is this large variation between consecutive frames.

**Comment by JawadTawhidi** [comment]
**Here I will upload those 10 masks after using DEVA's temporal propagation approach for davis 2017**


![00000](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/58fbd890-7c8a-4ef7-be88-24bb85cb4d7e)
![00001](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/f991b6a2-a09c-435c-ad60-0847dea4a824)
![00002](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/5a2c00f8-ed8a-4eb3-a625-b07d02752bb7)
![00003](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/7a9fb268-9e8b-4db2-8cc0-31ecf32fa610)
![00004](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/58e9d7aa-a667-4803-813d-c4de5540d918)
![00005](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/ecc0af92-a8b4-40a7-a1ca-37118700160b)
![00006](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/d8c41b68-1112-456f-8323-eeddd7fe8256)
![00007](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/66cfe135-c3a4-4b56-bacc-55e2a82d0e2d)
![00008](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/d8336e14-9511-4009-8581-cd808d6e66a4)
![00009](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/9006bc02-b7c4-4d5a-914c-0a5761400c1f)

**Comment by JawadTawhidi** [comment]
I know the segmentations generated by my model are affecting the DEAV's result, but still considering the large variation between consecutive frames in my videos(As you can see in the original annotations which I uploaded), I am thinking it is difficult even impossible for DEVA to reach in-clip Consensus. Even if DEVA reaches in-clip Consensus, the results will ignore a lots of useful information related to objects and that cause to incorrect prediction. 

**I want to mention one more while using DEVA's approach on DAVIS2017 I used this command:**
python evaluation/eval_with_detections.py  --mask_path /home/users/JawadT/Tracking-Anything-with-DEVA/15december/DAVIS16_val15december --img_path /home/users/JawadT/Tracking-Anything-with-DEVA/15december/DAVIS/JPEGImages/480p --dataset unsup_davis17 --temporal_setting semionline --output test --chunk_size 4

**Comment by hkchengrex** [comment]
Can you give more context (e.g. images) on what I'm looking at?

**Comment by JawadTawhidi** [comment]
Sure, but the in ultrasound images visual saliency is very low. It is difficult to distinguish between the object and its background by looking to the images.

**Comment by JawadTawhidi** [comment]
![00000](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/7f07a36c-1954-40cd-925b-1739f737ed86)
![00001](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/9c1e706a-e5fc-462d-9dd4-304b2857771b)
![00002](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/c47662d7-5692-41ff-8df8-eb7d093a6123)
![00003](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/23db719b-00fa-43a9-8eed-6056b773b4a7)
![00004](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/2236fbf8-a902-4315-bc25-a072ad5bbd7f)
![00005](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/049e6324-2a51-411f-86fe-55a7ff8cd2cb)
![00006](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/d09dc813-cb8a-46c1-b64c-3fa37bc2d0fe)
![00007](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/851b8256-3b94-4c90-ae48-96749e348c25)
![00008](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/a3981fc6-6251-4aaf-afb0-88e4a7a1b515)
![00009](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/133745795/804aa841-42ff-4625-b18e-184ac624b1aa)

**Comment by JawadTawhidi** [comment]
Here I have uploaded 10 images of those 10 annotations, but as I said in ultrasound images it is difficult to distinguish between the object and its background.

**Comment by hkchengrex** [comment]
If the images are too far away from the training domain, the propagation module might fail to track and DEVA might not work properly.

**Comment by JawadTawhidi** [comment]
The images are very close to training domain.

**Comment by JawadTawhidi** [comment]
Sorry, you mean my images are very far away from the data which you trained the DEVA's temporal propagation model?

**Comment by hkchengrex** [comment]
1. Yes.
2. Maybe?
3. That can also be a problem.

**Comment by JawadTawhidi** [comment]
Yes, my main concern is that even if I train the deva's temporal propagation model using ultrasound data, but while in-clip Consensus again that large variation between consecutive frames will decrease deva's performance results.
