### ISSUE TITLE
Deva out of memory

### ISSUE THREAD

**Issue by zhangzehao123** [hkchengrex/Tracking-Anything-with-DEVA#54]
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/117174448/c0794ca0-5477-4660-95a3-bd83f0fe731e)
Hello, when I try to find the dynamic masks of the video,my gpu memory was run out, how can i solve it? I used 4070 GPU.

Thank you！

**Comment by ekhaliul** [comment]
You can try adjusting some options SAM_NUM_POINTS_PER_BATCH=1, chunk_size=1, SAM_NUM_POINTS_PER_SIDE=32. It seem to work on my 3090 with ~26G.

**Comment by hkchengrex** [comment]
How can it be that the process is using 17179869184.00 GiB memory? This seems way off and I have no additional information. In general, there are several threads about memory consumption in this repo -- please utilize the search function and feel free to let me know if anything is still unclear.

**Comment by ekhaliul** [comment]
> How can it be that the process is using 17179869184.00 GiB memory? This seems way off and I have no additional information. In general, there are several threads about memory consumption in this repo -- please utilize the search function and feel free to let me know if anything is still unclear.

It seems like some output message bug in torch. I suppose they wanted to say `17179869184.00 B`.
