### ISSUE TITLE
Deva run out of memory with "Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use."

### ISSUE THREAD

**Issue by zhangzehao123** [hkchengrex/Tracking-Anything-with-DEVA#55]
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/117174448/9b864f8c-1b72-47fe-83be-248475a1b922)
Hello, when I try to find the dynamic masks of the video,my gpu memory was run out, how can i solve it? I used 4070 GPU.

Thank you！

**Comment by hkchengrex** [comment]
Duplicate #54
