### ISSUE TITLE
How to inference a video directly

### ISSUE THREAD

**Issue by wuyiqii** [hkchengrex/Tracking-Anything-with-DEVA#59]
First of all, thank you for your wonderful work, which is very helpful to my work。
I want to inference directly from one of my video data, what workflow should be used？
I've tried the demo_with_text.py，but it seems cannot identify my video file。

**Comment by hkchengrex** [comment]
You can convert your video to frames first, e.g., with ffmpeg.

**Comment by wuyiqii** [comment]
Thank you, it now works!
