### ISSUE TITLE
Deva on CPU

### ISSUE THREAD

**Issue by riccardo24-7** [hkchengrex/Tracking-Anything-with-DEVA#61]
Hi, How can I deploy the deva project on CPU. I have only errors connected with 

`ERROR Got unsupported ScalarType BFloat16`
or 
`ERROR Input type (torch.cuda.HalfTensor) and weight type (torch.FloatTensor) should be the same`

Thanks

**Comment by hkchengrex** [comment]
Hello.
We did not write the code with non-CUDA companionability in mind. It can be fixed by removing the autocast and the `.cuda()` calls.
