### ISSUE TITLE
Replace [grounding-dino+sam] with [yolo-world+efficient-sam]

### ISSUE THREAD

**Issue by guoqincode** [hkchengrex/Tracking-Anything-with-DEVA#66]
Thank you so much for your work, have you considered replacing [grounding-dino+sam] with [yolo-world+ Efficient-SAM], in many cases the latter is much faster with almost no impact on accuracy.

**Comment by hkchengrex** [comment]
Thank you for the suggestion. We currently have no plans to add any new extensions.
