### ISSUE TITLE
how to get the mask path to detections for rvos

### ISSUE THREAD

**Issue by xinbaiw** [hkchengrex/Tracking-Anything-with-DEVA#72]
Hello，how to get the mask path to detections for rvos， do you provider it? @hkchengrex 

![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/143494439/36c64d7b-66fc-4d9f-8074-998708737255)

**Comment by xinbaiw** [comment]
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/143494439/afb1dc57-c832-4fc9-a982-6be1cf415faf)

how to find the sores.csv?

**Comment by hkchengrex** [comment]
The download link is at the top of EVALUATION.md
Copied here: https://drive.google.com/drive/folders/1iBJBoKZAFaNYM_6uwBR0Vvc6q0nHXbFR?usp=sharing
