### ISSUE TITLE
Didn't you use a mask that was inferred from a large model during semi-youtubevos inference?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#75]
Didn't you use a mask that was inferred from a large model during semi-youtubevos inference? I see the script is not loading

![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/b8d777f7-f920-45e4-a0ce-b43b51536b0a)

**Comment by hkchengrex** [comment]
No. This is for semi-supervised VOS. Only the first-mask input is used.

**Comment by longmalongma** [comment]
> No. This is for semi-supervised VOS. Only the first-mask input is used.

Okay, for semi vos, how do we use the mask inferred by Sam? Is there a script like this?@hkchengrex

**Comment by hkchengrex** [comment]
We didn't test this application.
