### ISSUE TITLE
 0-5 represents the target?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#76]
This is the mask inferred using ReferFormer, where 0-5 represents the target? It seems like there are no six goals, only three objects？

![Uploading image.png…]()

**Comment by hkchengrex** [comment]
I cannot see your image.

**Comment by longmalongma** [comment]
> I cannot see your image.

0：
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/6e99ba86-887e-4abe-ae85-fd86f192cdaa)
1： 
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/201ba10f-e97c-4055-8183-c549537f0a58)
2：
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/d24631ba-ccb6-42e9-ad05-cbd183c21c9c)
3：
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/14388497-7e24-444c-a1cf-92082144e409)
4：
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/bcbb5e28-0e2d-4772-84bc-c02dc70f8dde)
5：
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/abdeba61-5df3-4f59-a582-1a7af1165046)
predicted mask:
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/a997e4d5-95cd-41ea-aaac-8f695f58cca8)
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/40291722/3a0dd624-33cc-4ee5-9af8-d0769dfce878)

**Comment by hkchengrex** [comment]
ReferFormer produces multiple masks in inference time. These are those masks. If you have a question about ReferFormer, it is probably best to refer to [ReferFormer](https://github.com/wjn922/ReferFormer)

**Comment by longmalongma** [comment]
> ReferFormer produces multiple masks in inference time. These are those masks. If you have a question about ReferFormer, it is probably best to refer to [ReferFormer](https://github.com/wjn922/ReferFormer)

Ok, thank you very much!
