### ISSUE TITLE
TrustImageSeg Inference

### ISSUE THREAD

**Issue by SangbeomLim** [hkchengrex/Tracking-Anything-with-DEVA#77]
Hello,

Firstly, thank you for sharing this impressive work and introducing us to DEVA.

I'm keen to reproduce the results related to the ablation study titled 'TrustImageSeg'. Could you please confirm if this feature is already implemented in the repository?

Thank you.

**Comment by hkchengrex** [comment]
Some code modification is needed which should be straightforward.
