### ISSUE TITLE
yolo_world with DEVA

### ISSUE THREAD

**Issue by LLH-Harward** [hkchengrex/Tracking-Anything-with-DEVA#78]
Hello,
    YOLO-World is a newly proposed real-time open-vocabulary object detection algorithm, which is 20 times faster than Grounding DINO while maintaining the same accuracy. Regarding how to integrate DEVA with YOLO-World, I have seen the CUSTOM.md file. Could you provide more guidance on this?

**Comment by hkchengrex** [comment]
Hi, 

Specifically, one would have to replace the function called here: 
https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/bb57c5241a144381fee911a097201acbcc29d592/deva/ext/with_text_processor.py#L58-L59

mask is an index mask (containing 0 for the background, and object id for the corresponding objects), and segments_info is a list of ObjectInfo defined in https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/inference/object_info.py#L7

Please feel free to let me know if there are any addition questions.

**Comment by LLH-Harward** [comment]
Thank you very much for your prompt reply. I will try it out.
