### ISSUE TITLE
U-net with DEVA

### ISSUE THREAD

**Issue by wkywwds** [hkchengrex/Tracking-Anything-with-DEVA#79]
How can I generate the  data format like `example/vipseg/source/12_1mWNahzcsAc` by U-net.

**Comment by hkchengrex** [comment]
Hi.
You can follow the data format and create the mask and `.json` files.
I can provide more information if you have more specific questions.

**Comment by wkywwds** [comment]
Can the "id" in the json file be defined manually, or must it be generated by my own detector? Also, when "isthing" is fasle, does it represent the background? If so, can I not mask the background?
Finally, what is the difference between the data formats in "vipseg" and "vos" and how are they used
![Uploading 9087689b74dd7debb764bd5f2184465.png…]()

**Comment by wkywwds** [comment]
![1](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/112048746/50dc4a5f-a51c-44bf-bba2-09965e4b4f7f)

**Comment by wkywwds** [comment]
> Hi. You can follow the data format and create the mask and `.json` files. I can provide more information if you have more specific questions.

Can the "id" in the json file be defined manually, or must it be generated by my own detector? Also, when "isthing" is fasle, does it represent the background? If so, can I not mask the background?
Finally, what is the difference between the data formats in "vipseg" and "vos" and how are they used

**Comment by hkchengrex** [comment]
1. Doesn't matter.
2. No. See the difference between thing and stuff in the COCO stuff paper.
3. VOS is for the VOS task. VIPSeg is for the video panoptic/unsupervised/universal segmentation task.

**Comment by wkywwds** [comment]
If it is said that the object of segmentation is not video, but a series of pictures, that is, the video is extracted frame by frame to generate a series of graphs. In this case, Need I detect all the images in the series and give each object in the picture an id?

**Comment by wkywwds** [comment]
> 1. Doesn't matter.
> 2. No. See the difference between thing and stuff in the COCO stuff paper.
> 3. VOS is for the VOS task. VIPSeg is for the video panoptic/unsupervised/universal segmentation task.
And Is the "isthing" referred to in the second point necessary?

**Comment by wkywwds** [comment]
> ![1](https://private-user-images.githubusercontent.com/112048746/321125624-50dc4a5f-a51c-44bf-bba2-09965e4b4f7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTU4NzksIm5iZiI6MTcxMjgxNTU3OSwicGF0aCI6Ii8xMTIwNDg3NDYvMzIxMTI1NjI0LTUwZGM0YTVmLWE1MWMtNDRiZi1iYmEyLTA5OTY1ZTRiNGY3Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNjA2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTNiZDRlZDE2ODA3MDUwZDBhMzhlYWQ4OThmMTVkNmFiODhiMmNlOThkY2ZmZDBiZDU2ZDMzNDAxZTFiNmYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aiRgeu0ifhRIXjw2alxsueH4b0kRzgG9yTZv3k8c4Rc)
How does the "id" associate with the masked objects in the image, such as horses and people
![00001258](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/112048746/91029b82-1304-49df-9945-e1bacbd9da5c)

**Comment by wkywwds** [comment]
![69e4dad47b12ea02ec52a7cefe3315f](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/112048746/91af9728-339e-460f-8f9e-8886af5f62bf)
I want to ask if this "--json_path" is a file directory or a file

**Comment by hkchengrex** [comment]
Directory.

**Comment by wkywwds** [comment]
Hello, when running the DEMO item in the file EVALUATION.md, why did the following error occur?The script's parameters are set to:
python eval_with_detections.py --mask_path "./example/vipseg/source" --img_path "./example/vipseg/images" --dataset demo --temporal_setting semionline --output "D:/Tracking-Anything-with-DEVA-main/example/output" --chunk_size 1

![24 04 13](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/112048746/b8db899c-ff92-44d9-b736-b364cd40e82f)

**Comment by hkchengrex** [comment]
We do not officially support Windows but I have pushed a fix that might help with your problem.
In the future, please open a separate issue for problems unrelated to this topic.
