### ISSUE TITLE
Information about the proposed method

### ISSUE THREAD

**Issue by lzl2040** [hkchengrex/Tracking-Anything-with-DEVA#8]
It seems that the proposed method is used during  the inference?

**Comment by hkchengrex** [comment]
I'm not sure if I understand your question.

**Comment by lzl2040** [comment]
> I'm not sure if I understand your question.

Sorry, maybe the question is not clear enough. What I want  to know is whether, in the video object segmentation task, the proposed bi-directional propagation, merging propagation and consensus are only used during the inference process .

**Comment by hkchengrex** [comment]
Thank you for the clarification. 
1. We would like to clarify that this method is for general video segmentation, not video object segmentation.
2. Only two modules require training: the image model for detection/segmentation, and the temporal propagation model. The segments merging and the consensus step do not have parameters that require training.
3. We have the training code for the temporal propagation module in this repo, but not the image model.
4. As a result, to extend this method to a new video segmentation task, one only needs to replace the image model -- no joint training is required.

**Comment by lzl2040** [comment]
Thanks for your answer!
