### ISSUE TITLE
extracting mask and bbox

### ISSUE THREAD

**Issue by shani1610** [hkchengrex/Tracking-Anything-with-DEVA#83]
Hi, Thank you for this work. 
I'm using the notebook you've shared and I'm trying to extract and save the masks and bounding boxes values, 
how can i do it? straight from result_saver? 

here is the snippet from the collab: 
![image](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/56839113/53ff719a-3e53-4ba9-b7fc-84d9612e4fa9)

Thank you!

**Comment by hkchengrex** [comment]
Yes. You would need to add a new mode in `result_saver` and specify that as `dataset` during ResultSaver initialization.
