### ISSUE TITLE
RuntimeWarning: Trying to segment without any memory!

### ISSUE THREAD

**Issue by Masrur02** [hkchengrex/Tracking-Anything-with-DEVA#84]
Hi, I am getting a Runtime warning; Trying to segment without any memory!, while I am trying to run the demo_automatic.py file. And after the completion of the code the outputs are not segmented. The outputs are simply the input images. I tried to play with the parameters also to reduce memory usage. My GPU is a Nvidia RTX 4090. How can I get rid of this problem? TIA

**Comment by hkchengrex** [comment]
That means the detector fails to detect anything. Are you running the script as-is?

**Comment by Masrur02** [comment]
Yes, I am Just following the instructions from your repo.

**Comment by hkchengrex** [comment]
I cannot reproduce this. Can you check if your SAM installation is working?

**Comment by Masrur02** [comment]
[image: image.png]
I think yes, the SAM installation is working

**Comment by hkchengrex** [comment]
I see. How about the other demo, i.e., `demo_with_text`?

**Comment by hkchengrex** [comment]
I haven't received anything. Feel free to reopen if needed.
