### ISSUE TITLE
The mask in example

### ISSUE THREAD

**Issue by wkywwds** [hkchengrex/Tracking-Anything-with-DEVA#87]
Is the mask shown below a platte mask
![00001255](https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/112048746/77f533ff-2a58-4781-9cec-a8c305a91dc8)

**Comment by hkchengrex** [comment]
Yes.

**Comment by hkchengrex** [comment]
Can you please use the same thread for the same issue? #85
