### ISSUE TITLE
SAM for the training sets of YouTube VOS and Davis 2017

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#89]
How to use SAM to infer masks on the training sets of YouTube VOS and Davis 2017? Can you provide guidance on how to do it specifically?

**Comment by hkchengrex** [comment]
I am not sure if I understand your question. If you just want to run SAM, you should use https://github.com/facebookresearch/segment-anything

**Comment by longmalongma** [comment]
> I am not sure if I understand your question. If you just want to run SAM, you should use https://github.com/facebookresearch/segment-anything

Ok, thanks!
