### ISSUE TITLE
No module named 'GroundingDINO'

### ISSUE THREAD

**Issue by huyuaaaray** [hkchengrex/Tracking-Anything-with-DEVA#9]
How are you, may I ask how to deal with the problem with 
```
    from GroundingDINO.groundingdino.util.inference import Model as GroundingDINOModel
ModuleNotFoundError: No module named 'GroundingDINO'
```

**Comment by hkchengrex** [comment]
Did you install Grounded-SAM?

**Comment by huyuaaaray** [comment]
Thanks, it works now! And is that necessary to use cuda when run the demo_gradio.py?

**Comment by hkchengrex** [comment]
The code is probably written in a way that requires cuda.

**Comment by hkchengrex** [comment]
It should be possible to modify it to run on CPU but that would be quite slow.

**Comment by zhoulele12** [comment]
where should we install Grounded-SAM

**Comment by hkchengrex** [comment]
@zhoulele12 Anywhere on your computer is fine.
