### ISSUE TITLE
Can deva be extended to video semantic segmentation and video instance segmentation tasks?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#92]
Can deva be extended to video semantic segmentation and video instance segmentation tasks? How to expand specifically?

**Comment by longmalongma** [comment]
Thanks for your reply. Could you provide some details on how to design some custom coding? We are now  following  your work.

**Comment by longmalongma** [comment]
Hello, can you help me?@hkchengrex

**Comment by hkchengrex** [comment]
Hi, 

The demo_automatic.py and demo_with_text.py are two examples.
