### ISSUE TITLE
reading data is particularly slow

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#94]
When running deva, reading data is particularly slow, which package in the deep learning environment may be the problem?

**Comment by hkchengrex** [comment]
It would depend on your system configuration. We use standard libraries for reading data.

**Comment by longmalongma** [comment]
> It would depend on your system configuration. We use standard libraries for reading data.

It's normal for me to run xmem, but I run devi slowly because reading data is slow. I don't know what the reason is?

**Comment by longmalongma** [comment]
Will changing the batch size from 16 to 18 and running with 6 cards result in performance loss? What modifications should I make accordingly?
