### ISSUE TITLE
 Will changing the batch size from 16 to 18 and running with 6 cards result in performance loss? 

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/Tracking-Anything-with-DEVA#96]
Will changing the batch size from 16 to 18 and running with 6 cards result in performance loss? What modifications should I make accordingly?

**Comment by hkchengrex** [comment]
You can change the number of GPUs according to this page https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/TRAINING.md

And the batch size in this page: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/utils/configuration.py

**Comment by longmalongma** [comment]
> You can change the number of GPUs according to this page https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/docs/TRAINING.md
> 
> And the batch size in this page: https://github.com/hkchengrex/Tracking-Anything-with-DEVA/blob/main/deva/utils/configuration.py

I know. Now I change the batch size to 18 and the number of Gpus to 6. Will this reduce the performance?

**Comment by hkchengrex** [comment]
I haven't tried it but I have no reason to believe that the performance would be significantly different.
