### ISSUE TITLE
Floor tracking is poor. Any suggestion?

### ISSUE THREAD

**Issue by garrisonz** [hkchengrex/Tracking-Anything-with-DEVA#98]
https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/1321005/6c8b59da-3ac1-4fcd-93b9-b3c6a9a0f7e3

Floor tracking is poor, especially in the lower right corner of the video.
Any suggestion? Thanks

This is the _bench_ scene in [3d_ovs dataset](https://drive.google.com/drive/folders/1kdV14Gu5nZX6WOPbccG7t7obP_aXkOuC)

**Comment by hkchengrex** [comment]
Thank you for sharing this. In general, background tracking and identical objects (i.e., the planks) are not well represented by the training dataset so they are hard. Secondly, using higher-frame-rate videos might improve the results.

**Comment by hkchengrex** [comment]
Which script are you using to generate this?

**Comment by garrisonz** [comment]
> Which script are you using to generate this?

```
python demo/demo_automatic.py --chunk_size 4 --img_path {img_path} --amp --temporal_setting semionline --size 480 --output {mask_root}
```

**Comment by hkchengrex** [comment]
The SAM output might be too inconsistent. Tracking similar background objects is also generally difficult.
