### ISSUE TITLE
How to Perform Inference on Multiple Videos?

### ISSUE THREAD

**Issue by weilllllls** [hkchengrex/Tracking-Anything-with-DEVA#99]
Hi, thanks for your great work! 

I find that the inference code only supports processing one video at a time. I modified the code to process multiple videos, like processing an entire dataset. However, I found that while the results for the first video were good, some problems occurred when processing the second and subsequent videos. I tried adjusting some parameter settings and found that this phenomenon might be related to buffer/memory issues. How should I modify my code?

I use 'online' mode and 'text-prompted'. The 'semionline' mode has the same problem.

The result of the first video's first frame:
<img width="256" alt="image" src="https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/60218260/d8df9298-1c9c-49b9-92d7-7935c9e31f95">
Then, process the second video's first frame:
<img width="256" alt="image" src="https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/60218260/b392bd8a-68de-4246-8f92-96bf330f39cd">

If I perform inference on the second video directly (no video was processed before), the result of the first frame looks good:
<img width="256" alt="image" src="https://github.com/hkchengrex/Tracking-Anything-with-DEVA/assets/60218260/625f1f6b-9a30-40b0-a9f0-4e9f4a5519cc">

**Comment by hkchengrex** [comment]
Thank you for your interest!
You can simply recreate a new `DEVAInferenceCore` instance (and `ResultSaver` if you are using it) for each video. All the internal states should be cleared.
